language: python
python:
- '3.5'
- '3.6'
- '3.7'
- '3.8'
- '3.9'
- '3.10'
- '3.11'
dist: bionic
sudo: true
matrix:
  fast_finish: true
install:
- if [[ $TRAVIS_PYTHON_VERSION == 3.7 ]]; then pip install -U importlib_metadata;
  fi
- pip install coverage coveralls
- pip install -e .
script:
- coverage run --source=pyblnet setup.py test
after_success:
- coverage report
- coveralls
deploy:
  provider: pypi
  on:
    branch: master
    python: '3.10'
  distributions: sdist bdist_wheel
  skip_existing: true
  username: "__token__"
  password:
    secure: byFAB9BEESb6x25aDAVH9vL3E3/qxCzsuKJ9eO8Aabj/5kTIccO5aoEDOsFChQvrRGtiBmy1Q6MUSyh0ifU1iyW+1dswTKJOJaMfhmbm0VtWOuQytDronhH+9rCRsOVXui2vT4eRuXRPGR4F1FtzaiuphpgZLZ1kGx5FQmdWYnIArQeSbra0i6+fnBr4qJrMjNUTwJWyFpdzHcPdaLy+NB6/LVHpbhyJmC9+oW217/Oq0II2h67gUHWR+cI/lHB853kvuSQrRs3XENSfMTGl4oX68N4zDQqbadRzdKzBGpVax9Klue4c9rlhoxAHS/NyjWSixMci/bzhkTYWURU8y4I/4VsZ1xwFQq3ev0wSYUmSsGVlnpqNR1UtJ5qdqP/k251MPOPtQwKSSKA4EOztmP1csM+OGLfvBAm8JRfRK6QanjjfHH8H6oLDmyRGwEGEoMUahIhydlsQAgWht3qYVU23aetGqAOgO87xsA826ZiZKTKlA1veCk10U77YKgg48pv4v0dQ7lS+0rgFyT81SFKvqS82uIQfd0H6QCQ8f8q9NTQofro/21eUjjhKPys0TKOBRIYAQN2pJYjF0E7uNqwIGZqxLqw/MdteEVYJr6dsdV9Sh015WFZIvuVxERr0uHsAbjVD1rDQM5OfIwgRTSOG63u+qRhFXyk5G8jbuzo=
