STATE = {'analog': {2: {'id': '2', 'name': 'TSP.oben', 'value': '47.1', 'unit_of_measurement': '°C'},
                    3: {'id': '3', 'name': 'TSP.unten', 'value': '57.8', 'unit_of_measurement': '°C'},
                    4: {'id': '4', 'name': 'THeizkr.VL', 'value': '45.8', 'unit_of_measurement': '°C'},
                    5: {'id': '5', 'name': 'Temp.Aussen', 'value': '1.1', 'unit_of_measurement': '°C'},
                    6: {'id': '6', 'name': 'Temp.Raum', 'value': '24.1', 'unit_of_measurement': '°C'},
                    7: {'id': '7', 'name': 'T\xa0Kaminofen', 'value': '55.8', 'unit_of_measurement': '°C'},
                    9: {'id': '9', 'name': 'TZirku.RL', 'value': '22.4', 'unit_of_measurement': '°C'}},
         'digital': {1: {'id': '1', 'name': 'Pumpe-Solar', 'mode': 'AUTO', 'value': 'AUS'},
                     2: {'id': '2', 'name': 'Pumpe-Hzkr', 'mode': 'AUTO', 'value': 'EIN'},
                     5: {'id': '5', 'name': 'Anf.Kessel', 'mode': 'AUTO', 'value': 'AUS'},
                     6: {'id': '6', 'name': 'Vent.Solar', 'mode': 'HAND', 'value': 'AUS'},
                     7: {'id': '7', 'name': 'P\xa0Kaminofen', 'mode': 'AUTO', 'value': 'EIN'},
                     10: {'id': '10', 'name': 'WW-Pumpe1', 'mode': 'HAND', 'value': 'AUS'}}, 'speed': {}, 'energy': {},
         'power': {}}
